### ISSUE TITLE
virtualbox ubuntu配置双向通信和代理

### ISSUE THREAD

**Issue by Kila2** [Kila2/KilaNote#23]
# 关闭防火墙 简单点可以直接关闭虚拟机防火墙。也可以通过iptables配置22端口
sudo ufw disbale
# 开启防火墙
sudo ufw enable
# 开启22端口
sudo iptables -A INPUT -p tcp --dport 22 -j ACCEPT
# 仅对某ip开启22端口
sudo iptables -A INPUT -p tcp -s <you IP> --dport 22 -j ACCEPT
# virtualbox 配置双网卡
![image](https://user-images.githubusercontent.com/7580754/122254088-5c923480-ceff-11eb-9876-ebb68e50bf80.png)
![image](https://user-images.githubusercontent.com/7580754/122254120-63b94280-ceff-11eb-8570-28628f9b0382.png)
如果host-only无法添加。需要先创建一个到偏好设置-网络中添加一个网络。
# 配置好网卡后到虚拟机中配置ip 注意名字要匹配
```
$ls /sys/class/net
```
```
docker0  enp0s3  enp0s8  lo
```
```
$sudo vi /etc/netplan/00-installer-config.yaml
```
注意如果是安装好系统后添加的网卡。配置文件中可能没有第二块网卡，需要自己填写。
```
# This is the network config written by 'subiquity' 
network:
  ethernets:
    enp0s3:
      dhcp4: false
      addresses:
          - 192.168.56.12/24
    enp0s8:
      dhcp4: true
  version: 2
```
# 让配置生效
```
sudo netplan generate
sudo netplan apply
```
这时应该可以在主机通过ssh登陆虚拟机了。
# 设置host的http代理可能无法访问
可以尝试更改配置文件中的127.0.0.1改为局域网ip。然后重启服务。之后虚拟机可以通过下面的代码访问代理了
```
export http_proxy=http://<ip:port>;export https_proxy=https://<ip:port>;
```
# 共享文件夹需要安装软件
```
sudo apt-get install virtualbox-guest-utils
```
# 开机自启动
注意`sudo vi /etc/vbox/autostart.cfg`时替换成自己的用户名
[https://gist.github.com/str8edgedave/b0b96e12396aaa7d383456778079ee7b](https://gist.github.com/str8edgedave/b0b96e12396aaa7d383456778079ee7b)
